-  name: demo on condition
   hosts: localhost
   tasks:
     -  name: say hai to john
        ansible.builtin.debug:
          msg: hey, john
        when: user == "john"

     -  name: say hii to ram
        ansible.builtin.debug:
          msg: hey, ram
        when: user == "ram"