-  name: demo on filters
   hosts: localhost
   vars:
     URL : https://nginx.org/download/nginx-1.25.3.zip
   tasks:
     -  name: filters
        ansible.builtin.unarchive:
          src: "{{ URL }}"
          dest: /tmp
          remote_src: true


     -  name: url split
        ansible.builtin.debug:
          msg: "{{ URL | split ('/') | last }}"
